version: '2'

services:
  storm:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    tty: true
    stdin_open: true
    volumes:
      - "~/.storm:/root/.storm"
      - "~/.docker/machine:/root/.docker/machine"
